## 라이브러리

In [20]:
import os
import numpy as np
import pandas as pd
from datetime import datetime

## 경로

In [21]:
DATA_DIR = "../data_nongsanmul"
TRAIN_PATH = os.path.join(DATA_DIR, "train.csv")

## DATA

In [65]:
pd.set_option('display.max_columns', None)

In [66]:
df = pd.read_csv(TRAIN_PATH, parse_dates=["date"])
df.head()

,date,요일,배추_거래량(kg),배추_가격(원/kg),무_거래량(kg),무_가격(원/kg),양파_거래량(kg),양파_가격(원/kg),건고추_거래량(kg),건고추_가격(원/kg),마늘_거래량(kg),마늘_가격(원/kg),대파_거래량(kg),대파_가격(원/kg),얼갈이배추_거래량(kg),얼갈이배추_가격(원/kg),양배추_거래량(kg),양배추_가격(원/kg),깻잎_거래량(kg),깻잎_가격(원/kg),시금치_거래량(kg),시금치_가격(원/kg),미나리_거래량(kg),미나리_가격(원/kg),당근_거래량(kg),당근_가격(원/kg),파프리카_거래량(kg),파프리카_가격(원/kg),새송이_거래량(kg),새송이_가격(원/kg),팽이버섯_거래량(kg),팽이버섯_가격(원/kg),토마토_거래량(kg),토마토_가격(원/kg),청상추_거래량(kg),청상추_가격(원/kg),백다다기_거래량(kg),백다다기_가격(원/kg),애호박_거래량(kg),애호박_가격(원/kg),캠벨얼리_거래량(kg),캠벨얼리_가격(원/kg),샤인마스캇_거래량(kg),샤인마스캇_가격(원/kg)
0,2016-01-01,금요일,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2016-01-02,토요일,80860.0,329.0,80272.0,360.0,122787.5,1281.0,3.0,11000.0,15019.0,5475.0,92334.0,1704.0,6359.0,1331.0,40028.0,348.0,4374.9,13242.0,16550.5,2339.0,10528.0,1729.0,13885.0,804.0,3853.0,3703.0,15797.0,2576.0,14634.0,1474.0,30950.0,1621.0,5125.0,9235.0,434.0,2109.0,19159.0,2414.0,880.0,2014.0,0.0,0.0
2,2016-01-03,일요일,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2016-01-04,월요일,1422742.5,478.0,1699653.7,382.0,2315079.0,1235.0,699.0,4464.0,141638.0,5210.0,994328.1,1716.0,262615.5,1212.0,1074699.1,345.0,122613.5,9923.0,427435.1,2153.0,82113.5,3960.0,558950.2,794.0,104930.3,4871.0,277326.5,2440.0,159800.0,1750.0,291057.0,1834.0,38525.5,7631.0,500702.0,2046.0,620539.0,2018.0,2703.8,3885.0,0.0,0.0
4,2016-01-05,화요일,1167241.0,442.0,1423482.3,422.0,2092960.1,1213.0,1112.6,4342.0,126207.8,5387.0,787716.0,1715.0,221850.5,1197.0,825681.9,350.0,79055.9,9529.0,334636.8,2220.0,80144.0,3333.0,444353.7,763.0,100699.5,5129.0,218465.2,2437.0,153084.0,1822.0,194626.5,1833.0,32615.0,6926.0,147638.0,2268.0,231958.0,2178.0,8810.0,2853.0,0.0,0.0

In [56]:
df = df.set_index(["date"])

In [62]:
(df == 0).sum()
# 품목별로 0의 개수가 다르기 때문에, 한번에 0 값들을 제거하고 시작하는 게 아니라
# 원하는 품목을 정하고 그 품목에 대한 데이터프레임만을 새로 만들고 나서 0 값을 제거하는 게 좋을 듯

요일                  0
배추_거래량(kg)        253
배추_가격(원/kg)       253
무_거래량(kg)         254
무_가격(원/kg)        254
양파_거래량(kg)        255
양파_가격(원/kg)       255
건고추_거래량(kg)       274
건고추_가격(원/kg)      274
마늘_거래량(kg)        265
마늘_가격(원/kg)       265
대파_거래량(kg)        254
대파_가격(원/kg)       254
얼갈이배추_거래량(kg)     261
얼갈이배추_가격(원/kg)    261
양배추_거래량(kg)       258
양배추_가격(원/kg)      258
깻잎_거래량(kg)        254
깻잎_가격(원/kg)       254
시금치_거래량(kg)       257
시금치_가격(원/kg)      257
미나리_거래량(kg)       260
미나리_가격(원/kg)      260
당근_거래량(kg)        262
당근_가격(원/kg)       262
파프리카_거래량(kg)      265
파프리카_가격(원/kg)     265
새송이_거래량(kg)       258
새송이_가격(원/kg)      258
팽이버섯_거래량(kg)      265
팽이버섯_가격(원/kg)     265
토마토_거래량(kg)       258
토마토_가격(원/kg)      258
청상추_거래량(kg)       259
청상추_가격(원/kg)      259
백다다기_거래량(kg)      263
백다다기_가격(원/kg)     263
애호박_거래량(kg)       258
애호박_가격(원/kg)      258
캠벨얼리_거래량(kg)      305
캠벨얼리_가격(원/kg)     305
샤인마스캇_거래량(kg)     811
샤인마스캇_가격(원/kg)    811
dtype: int64